### ISSUE TITLE
include deprecated locales: iw in ji

### ISSUE THREAD

**Issue by eighthave** [umpirsky/language-list#13]
There are three locales that were used in Java and still show up on Android devices:
* _iw_ used to be for Hebrew
* _in_ used to be for Indonesian
* _ji_ used to be for Yiddish

Some references:
* https://stackoverflow.com/a/13974180
* https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#special_cases_constructor

**Comment by umpirsky** [comment]
Thanks, but this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.
