### ISSUE TITLE
Composer usage

### ISSUE THREAD

**Issue by jsgv** [umpirsky/language-list#15]
How is this package meant to be used? 
Possibly add some examples?
I tried to use `bin/build`, but got error.

`php vendor/umpirsky/language-list/bin/build`

```
Warning: include(/var/www/vendor/umpirsky/language-list/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vendor/umpirsky/language-list/bin/build on line 4

Warning: include(): Failed opening '/var/www/vendor/umpirsky/language-list/bin/../vendor/autoload.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/www/vendor/umpirsky/language-list/bin/build on line 4

Fatal error: Uncaught Error: Class 'Umpirsky\ListGenerator\Importer\Importer' not found in /var/www/vendor/umpirsky/language-list/bin/build:6
Stack trace:
#0 {main}
  thrown in /var/www/vendor/umpirsky/language-list/bin/build on line 6
```

**Comment by umpirsky** [comment]
Just run `php composer.phar install`.

For more information, see https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies

**Comment by jsgv** [comment]
Sorry, let me explain some more.

I have installed this package with composer `composer require umpirsky/language-list`. It is installed in vendor. 

My question is how the package is meant to be consumed after it has been installed.

**Comment by umpirsky** [comment]
Describe your use case please. You can use it in many ways, one of them is `$languages = include 'language-list/data/en/language.php'`.
