### ISSUE TITLE
Can you recommend a list of contemporary languages

### ISSUE THREAD

**Issue by sandervanhooft** [umpirsky/language-list#17]
Hi @umpirsky ,

This package is great but also includes "dead languages". Can you perhaps recommend a similar list of only contemporary languages? Or a way to generate it?

**Comment by umpirsky** [comment]
No, sorry.

**Comment by sandervanhooft** [comment]
No problem. I’ve found this, it may be of help to others as well:


https://github.com/annexare/Countries/blob/master/data/languages.json
