### ISSUE TITLE
Complete list as sql (mysql)?

### ISSUE THREAD

**Issue by Ericmuc** [umpirsky/language-list#18]
Hi,
I am wondering whether it is possible to get (or to can download) a file with all language translations?
I would need this for my website for a query field, bt don't know how to handle this code here.
Thanks, best regards
Eric

**Comment by umpirsky** [comment]
Hi. You can download them separately and merge into single file if that's what you need.

**Comment by Ericmuc** [comment]
Hi, Thanks for the quick answer and thank you very much for having this possibility. Ok, I will do so, thanks, best regards
Eric
